Update ci.yml build merge

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,5 +1,3 @@
-# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
 
 name: TalkAi CI
 
@@ -28,3 +26,25 @@ jobs:
     - name: Install dependencies
       run: yarn install
     - run: yarn build
+
+  merge-check:
+    needs: build
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v2
+
+      - name: Set up Git
+        run: |
+          git config user.name github-actions
+          git config user.email github-actions@github.com
+
+      - name: Merge Check
+        run: |
+          if [ "${{ needs.build-and-test.outcome }}" == "failure" ]; then
+            echo "CI Build and Test failed. Aborting merge."
+            exit 1
+          else
+            echo "CI Build and Test passed. Ready for merge."
+          fi
